---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:9000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <use `bundle exec rake generate:session_secret`>

test:
  API_URL: http://localhost:9000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <use `bundle exec rake generate:session_secret`>

production:
  API_URL: <set to production API root>
  APP_URL: <set to production app URL>
  SESSION_SECRET: <use `bundle exec rake generate:session_secret`>
